config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
	root 'static_pages#home'
  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'sign_up' => 'users#new'
  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy'
  get 'api/relationships'
  get 'api/user'
  post 'api/chats'
  get 'api/feed'
  post 'api/submit_chat'
  resources :users do
  	member do
  		get :following, :followers
  	end
  end
  resources :account_activations, only: :edit
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :chats, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  

end

app/views/shared/_call_to_action.html.erb
<div class="center jumbotron">
	<h1>welcome to chttr</h1>
	<h2>A place for groups.</h2>
	<%= link_to "Get started!", sign_up_path, class: "btn btn-lg btn-primary" %>
	<h6><%= link_to "Or sign in.", sign_in_path %></h6>
</div>
<blockquote>
	<p>Proudly built and powered with:</p>
	<%= link_to image_tag("rails.png", alt: "Built with Ruby on Rails"), 'http://rubyonrails.org/' %>
</blockquote>

app/views/shared/_chat_form.html.erb
<%= form_for(@chat, html: { multipart: true }) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_area :content, placeholder: "Share something new..." %>
	</div>
	<%= f.submit "Post", class: "btn btn-primary" %>
	<span class="picture">
		<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
	</span>
<% end %>

<script type="text/javascript">
  $('#chat_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_dashboard.html.erb
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<%= render 'shared/user_info' %>			
		</section>
		<section class="stats">
			<%= render 'shared/stats' %>
		</section>
		<section class="chat_form">
			<%= render 'shared/chat_form' %>
		</section>			
	</aside>
	<div class="col-md-8">
		<h3>Chats</h3>
		<%= render 'shared/feed' %>
	</div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			<ul>
				<% object.errors.full_messages.each do |msg| %>
					<li>
						<%= msg %>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="chats">
		<%= render @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat"><%= @user.following.count %></strong> following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat"><%= @user.followers.count %></strong> followers
	</a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.chats.count, "chat") %> since <%= time_ago_in_words(current_user.created_at) %></span>